apiVersion: v1
kind: Namespace
metadata:
  name: hyperfleet
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hyperfleet-e2e-adapter
  namespace: hyperfleet
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hyperfleet-e2e-adapter-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: hyperfleet-e2e-adapter
    namespace: hyperfleet
